### ISSUE TITLE
[Public] [Informatii] & [Resurse de sprijin] Seems like the info here is not taken from the Admin dashboard

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/adapt-just-front#10]
**Describe the bug**
There are articles added from the Admin dashboard that are visible on mobile, but not here. 

**Expected behavior**
All the information from the admin dashboard should be visible in the public platform as well as the mobile app.

**Comment by jacobcatalin** [comment]
as I see now, it doesn't show articles or resources in the mobile app, but the mobile app in calling the api.adaptjust.ro endpoint. As the domain was changed to cerajutor.ro , we need to make a new build for the app  to change the api endpoint
