### ISSUE TITLE
Need to add a new logo in footer & About page

### ISSUE THREAD

**Issue by mirunaioana-msc** [code4romania/adapt-just-front#15]
We need to add an additional logo on the about Page and footer

Footer 
<img width="965" alt="Screenshot 2023-12-04 at 15 06 37" src="https://github.com/code4romania/adapt-just-front/assets/111346300/0cf99931-2d07-424d-a2de-55e1ab088e0b">

About page
<img width="605" alt="Screenshot 2023-12-04 at 15 09 15" src="https://github.com/code4romania/adapt-just-front/assets/111346300/6943d1be-65d6-4f66-80f6-fd82dabc4eb9">

**Comment by jacobcatalin** [comment]
@mirunaioana-msc done on staging environment
